FROM postgres:12
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt -y install pgagent 
RUN apt update && apt -y install wget && apt install vim -y
RUN apt update && apt -y install postgresql-server-dev-12

